### PR TITLE
fix: empty username

### PR DESCRIPTION
**Pull request by rafiramadhana**
Issue: #50 

Fix empty username when full name is more than 10 chars.

### CODE REVIEW

**Review by nekomeowww — APPROVED** [review]

**Comment by nekomeowww** [comment]
Thank you for contribution!

**Comment by rafiramadhana** [comment]
@nekomeowww No worries. Btw just curious, is the token you mentioned relates to GPT products?

**Comment by nekomeowww** [comment]
> @nekomeowww No worries. Btw just curious, is the token you mentioned relates to GPT products?

Yes, you can learn more from: 

- https://platform.openai.com/tokenizer
- https://github.com/pkoukk/tiktoken-go

**Comment by rafiramadhana** [comment]
@nekomeowww This project seems interesting.

Is this bot feature mainly about summarizing articles on the web?

I've just tried your bot on Telegram. However, I am using google translate when trying your bot (including when reading the `/help` output). CMIIW if I am missing something related to the feature.

**Comment by nekomeowww** [comment]
> @nekomeowww This project seems interesting.
> 
> 
> 
> Is this bot feature mainly about summarizing articles on the web?

Yes! The /smr command is used to summarize the link you send to the bot, and then the bot will fetch and summarize the contents of the web page into a brief summary with three following question to the contents. The /recap command is used to summarize the chat histories in Telegram groups to produce a recapture to what everyone was talking about during past hours.

Currently, we are focusing on improving the quality of chat history recapturing feature, and trying to extend the summarization feature by borrowing some of the langchain concepts.

> I've just tried your bot on Telegram. However, I am using google translate when trying your bot (including when reading the `/help` output). CMIIW if I am missing something related to the feature.

Wow, how did you find the bot? Sorry to hear about the bad i18n user experience, we may have to start to work on i18n to support more languages.

**Comment by rafiramadhana** [comment]
> Wow, how did you find the bot? Sorry to hear about the bad i18n user experience, we may have to start to work on i18n to support more languages.

I clicked the telegram _badge_ in this repo.

Ok. Thanks for the explanation.

**Pull request merged**
